In [1]:
import numpy as np
import tensorflow as tf


In [ ]:
@tf.function
def forward():
  in_channels = 1 # 3 for RGB, 32, 64, 128, ... 
  out_channels = 1 # 128, 256, ...
  bias = np.array([2
  ])

  # kernel in Figure 4-8(b)
  ones_3d = np.array([
       [2,2,2,2,2,1,1,1],
       [2,2,2,2,2,1,1,1],
       [2,2,2,2,2,1,1,1],
       [2,2,2,2,2,1,1,1],
       [2,2,2,9,9,9,9,9],
       [2,2,2,9,9,9,9,9],
       [2,2,2,9,9,9,9,9],
       [2,2,2,9,9,9,9,9]
               
])
    
  weight_4d = np.array([
      [-1,0,1],
      [-1,0,1],
      [-1,0,1],          
  ])
  strides_2d = [1, 1, 1, 1] 

  in_3d = tf.constant(ones_3d, dtype=tf.float32)
  filter_4d = tf.constant(weight_4d, dtype=tf.float32)

  in_width = int(in_3d.shape[0])
  in_height = int(in_3d.shape[1])

  filter_width = int(filter_4d.shape[0])
  filter_height = int(filter_4d.shape[1])

  input_3d   = tf.reshape(in_3d, [1, in_height, in_width, in_channels])
  kernel_4d = tf.reshape(filter_4d, [filter_height, filter_width, in_channels, out_channels])

  #output stacked shape is 3D = 2D x N matrix
  # "SAME" = with zero padding
  output_3d = tf.nn.conv2d(input_3d, kernel_4d, strides=strides_2d, padding='SAME')
  output_3d = tf.nn.bias_add(output_3d, bias)
  return output_3d # size is height x width x channels x number of filters).
result = forward()
print(result)

## To realize the Figure in pg198 4(b) 

In [63]:
in_channels = 1 # 3 for RGB, 32, 64, 128, ... 
out_channels = 1 # 128, 256, ...
bias = np.array([2
])

# kernel in Figure 4-8(b)
ones_3d = np.array([
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9]
            
])

weight_4d = np.array([
    [-1,0,1],
    [-1,0,1],
    [-1,0,1],          
])
strides_2d = [1, 1, 1, 1] # [batch stride, height stride, width stride, channel stride]

in_3d = tf.constant(ones_3d, dtype=tf.float32)
filter_4d = tf.constant(weight_4d, dtype=tf.float32)

in_width = int(in_3d.shape[0])
in_height = int(in_3d.shape[1])

filter_width = int(filter_4d.shape[0])
filter_height = int(filter_4d.shape[1])

input_3d   = tf.reshape(in_3d, [1, in_height, in_width, in_channels])
kernel_4d = tf.reshape(filter_4d, [filter_height, filter_width, in_channels, out_channels])

#output stacked shape is 3D = 2D x N matrix
# "VALID" = without padding
output_3d = tf.nn.conv2d(input_3d, kernel_4d, strides=strides_2d, padding='VALID')
output_3d = tf.nn.bias_add(output_3d, bias)
output_3d 


<tf.Tensor: shape=(1, 6, 6, 1), dtype=float32, numpy=
array([[[[ 2.],
         [ 2.],
         [ 2.],
         [-1.],
         [-1.],
         [ 2.]],

        [[ 2.],
         [ 2.],
         [ 2.],
         [-1.],
         [-1.],
         [ 2.]],

        [[ 2.],
         [ 9.],
         [ 9.],
         [ 0.],
         [ 0.],
         [ 2.]],

        [[ 2.],
         [16.],
         [16.],
         [ 1.],
         [ 1.],
         [ 2.]],

        [[ 2.],
         [23.],
         [23.],
         [ 2.],
         [ 2.],
         [ 2.]],

        [[ 2.],
         [23.],
         [23.],
         [ 2.],
         [ 2.],
         [ 2.]]]], dtype=float32)>

## Question 3
### Zero-Padding and 0.5 bias

In [94]:
in_channels = 1 # 3 for RGB, 32, 64, 128, ... 
out_channels = 1 # 128, 256, ...
bias = np.array([0.5
])

# kernel in Figure 4-8(b)
ones_3d = np.array([
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9]
            
])
# weight_4d = np.array([
#     [-1,0,1],
#     [-1,0,1],
#     [-1,0,1],          
# ])

weight_4d = np.array([
      [-1,-1,-1],
      [0,0,0],
      [1,1,1],      
])
strides_2d = [1, 1, 1, 1]  # [batch stride, height stride, width stride, channel stride]

in_3d = tf.constant(ones_3d, dtype=tf.float32)
filter_4d = tf.constant(weight_4d, dtype=tf.float32)

in_width = int(in_3d.shape[0])
in_height = int(in_3d.shape[1])

filter_width = int(filter_4d.shape[0])
filter_height = int(filter_4d.shape[1])

input_3d   = tf.reshape(in_3d, [1, in_height, in_width, in_channels])
kernel_4d = tf.reshape(filter_4d, [filter_height, filter_width, in_channels, out_channels])


#output stacked shape is 3D = 2D x N matrix
# "SAME" = zero padding
# "SAME" = zero padding
output_3d_1 = tf.nn.conv2d(input_3d, kernel_4d, strides=strides_2d, padding='SAME')
output_3d_1 = tf.nn.bias_add(output_3d_1, bias)
output_3d_1



<tf.Tensor: shape=(1, 8, 8, 1), dtype=float32, numpy=
array([[[[  4.5],
         [  6.5],
         [  6.5],
         [  6.5],
         [  5.5],
         [  4.5],
         [  3.5],
         [  2.5]],

        [[  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5]],

        [[  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5]],

        [[  0.5],
         [  0.5],
         [  7.5],
         [ 14.5],
         [ 22.5],
         [ 23.5],
         [ 24.5],
         [ 16.5]],

        [[  0.5],
         [  0.5],
         [  7.5],
         [ 14.5],
         [ 22.5],
         [ 23.5],
         [ 24.5],
         [ 16.5]],

        [[  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5],
         [  0.5]],

        [[  0.5],
         [  0.5],
         [  0.5],
         [  0.5]

## Question 4
### stride with 2

In [83]:
in_3d.shape

TensorShape([8, 8])

In [84]:
input_3d

<tf.Tensor: shape=(1, 8, 8, 1), dtype=float32, numpy=
array([[[[2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [1.],
         [1.],
         [1.]],

        [[2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [1.],
         [1.],
         [1.]],

        [[2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [1.],
         [1.],
         [1.]],

        [[2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [1.],
         [1.],
         [1.]],

        [[2.],
         [2.],
         [2.],
         [9.],
         [9.],
         [9.],
         [9.],
         [9.]],

        [[2.],
         [2.],
         [2.],
         [9.],
         [9.],
         [9.],
         [9.],
         [9.]],

        [[2.],
         [2.],
         [2.],
         [9.],
         [9.],
         [9.],
         [9.],
         [9.]],

        [[2.],
         [2.],
         [2.],
         [9.],
         [9.],
         [9.],
  

In [89]:
filter_4d.shape

TensorShape([3, 3])

In [93]:
kernel_4d.shape

TensorShape([3, 3, 1, 1])

In [186]:
in_channels = 1 # 3 for RGB, 32, 64, 128, ... 
out_channels = 1 # 128, 256, ...
bias = np.array([0.5
])

# KERNEL RESULT FROM PREVIOUS QUESTION
ones_3d = np.array([
       [2,2,2,2,2,1,1,1],
       [2,2,2,2,2,1,1,1],
       [2,2,2,2,2,1,1,1],
       [2,2,2,2,2,1,1,1],
       [2,2,2,9,9,9,9,9],
       [2,2,2,9,9,9,9,9],
       [2,2,2,9,9,9,9,9],
       [2,2,2,9,9,9,9,9]
               
])

# weight_4d = np.array([
#     [-1,0,1],
#     [-1,0,1],
#     [-1,0,1],          
# ])
weight_4d = np.array([
      [-1,-1,-1],
      [0,0,0],
      [1,1,1],      
])
strides_2d = [1, 1, 1, 1] # [batch stride, height stride, width stride, channel stride]
in_3d = tf.constant(ones_3d, dtype=tf.float32)
filter_4d = tf.constant(weight_4d, dtype=tf.float32)

filter_width = int(filter_4d.shape[0])
filter_height = int(filter_4d.shape[1])

input_3d   = tf.reshape(in_3d, [1, in_height, in_width, in_channels])
kernel_4d = tf.reshape(filter_4d, [filter_height, filter_width, in_channels, out_channels]) # [height, width, in channels, out channels] 

#output stacked shape is 3D = 2D x N matrix
# "SAME" = with zero padding
# output_3d_2  = tf.nn.conv2d(input_3d, filters=kernel_4d, strides=strides_2d, padding='SAME')
# output_3d_1 = tf.nn.conv2d(input_3d, kernel_4d, strides=strides_2d, padding='SAME')
# output_3d_1 = tf.nn.bias_add(output_3d_1, bias)
# output_3d_2  = tf.nn.conv2d(output_3d_1 , filters=kernel_4d, strides=[1, 2, 2, 1], padding='SAME')
# output_3d_2   = tf.nn.bias_add(output_3d_2  , bias)
output_3d_2 = tf.nn.conv2d(input_3d, kernel_4d, strides=[1, 2, 2, 1], padding='SAME') # with stride length 2 x 2
output_3d_2   = tf.nn.bias_add(output_3d_2  , bias)

output_3d_2 

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[  0.5],
         [  0.5],
         [  0.5],
         [  0.5]],

        [[  0.5],
         [ 14.5],
         [ 23.5],
         [ 16.5]],

        [[  0.5],
         [  0.5],
         [  0.5],
         [  0.5]],

        [[ -5.5],
         [-19.5],
         [-26.5],
         [-17.5]]]], dtype=float32)>

## Question 5
### Max pooling

In [145]:
in_channels = 1 # 3 for RGB, 32, 64, 128, ... 
out_channels = 1 # 128, 256, ...
bias = np.array([0.5
])

# kernel in Figure 4-8(b)
ones_3d = np.array([
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9]
            
])
# weight_4d = np.array([
#     [-1,0,1],
#     [-1,0,1],
#     [-1,0,1],          
# ])

weight_4d = np.array([
      [-1,-1,-1],
      [0,0,0],
      [1,1,1],      
])
strides_2d = [1, 1, 1, 1]  # [batch stride, height stride, width stride, channel stride]

in_3d = tf.constant(ones_3d, dtype=tf.float32)
filter_4d = tf.constant(weight_4d, dtype=tf.float32)

in_width = int(in_3d.shape[0])
in_height = int(in_3d.shape[1])

filter_width = int(filter_4d.shape[0])
filter_height = int(filter_4d.shape[1])

input_3d   = tf.reshape(in_3d, [1, in_height, in_width, in_channels])


#output stacked shape is 3D = 2D x N matrix
# "SAME" = zero padding
# "SAME" = zero padding
output_3d_3 = tf.nn.conv2d(input_3d, filters=kernel_4d, strides=strides_2d, padding='SAME')
output_3d_3  = tf.nn.bias_add(output_3d_3 , bias)
output_3d_3  = tf.nn.max_pool(output_3d_3 , ksize = [1, 3, 3, 1], strides=[1, 1, 1, 1], padding='SAME') # use a 3 by 3 filter # stride = 1
output_3d_3 

<tf.Tensor: shape=(1, 8, 8, 1), dtype=float32, numpy=
array([[[[ 6.5],
         [ 6.5],
         [ 6.5],
         [ 6.5],
         [ 6.5],
         [ 5.5],
         [ 4.5],
         [ 3.5]],

        [[ 6.5],
         [ 6.5],
         [ 6.5],
         [ 6.5],
         [ 6.5],
         [ 5.5],
         [ 4.5],
         [ 3.5]],

        [[ 0.5],
         [ 7.5],
         [14.5],
         [22.5],
         [23.5],
         [24.5],
         [24.5],
         [24.5]],

        [[ 0.5],
         [ 7.5],
         [14.5],
         [22.5],
         [23.5],
         [24.5],
         [24.5],
         [24.5]],

        [[ 0.5],
         [ 7.5],
         [14.5],
         [22.5],
         [23.5],
         [24.5],
         [24.5],
         [24.5]],

        [[ 0.5],
         [ 7.5],
         [14.5],
         [22.5],
         [23.5],
         [24.5],
         [24.5],
         [24.5]],

        [[ 0.5],
         [ 0.5],
         [ 0.5],
         [ 0.5],
         [ 0.5],
         [ 0.5],
         [ 0.5],

### Average pooling

In [198]:
in_channels = 1 # 3 for RGB, 32, 64, 128, ... 
out_channels = 1 # 128, 256, ...
bias = np.array([0.5
])

# kernel in Figure 4-8(b)
ones_3d = np.array([
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,2,2,1,1,1],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9],
    [2,2,2,9,9,9,9,9]
            
])
# weight_4d = np.array([
#     [-1,0,1],
#     [-1,0,1],
#     [-1,0,1],          
# ])

weight_4d = np.array([
      [-1,-1,-1],
      [0,0,0],
      [1,1,1],      
])
strides_2d = [1, 1, 1, 1]  # [batch stride, height stride, width stride, channel stride]

# in_3d = tf.constant(ones_3d, dtype=tf.float32)
filter_4d = tf.constant(weight_4d, dtype=tf.float32)

in_width = int(in_3d.shape[0])
in_height = int(in_3d.shape[1])

filter_width = int(filter_4d.shape[0])
filter_height = int(filter_4d.shape[1])

input_3d   = tf.reshape(in_3d, [1, in_height, in_width, in_channels])
kernel_4d = tf.reshape(filter_4d, [filter_height, filter_width, in_channels, out_channels])
# input_3d = output_3d_1

#output stacked shape is 3D = 2D x N matrix
# "SAME" = zero padding
output_3d_4 = tf.nn.conv2d(input_3d, kernel_4d, strides=strides_2d, padding='SAME') # output_3d_3 
output_3d_4  = tf.nn.bias_add(output_3d_4 , bias)
avg_pool_2d = tf.keras.layers.AveragePooling2D(pool_size=(3, 3),strides=(1, 1) ,padding='SAME')
x = avg_pool_2d(output_3d_4) 
# output_3d_4  = tf.nn.avg_pool(output_3d_4  , ksize = [1, 3, 3, 1], strides=[1, 1, 1, 1], padding='SAME') # use a 3 by 3 filter # stride = 1 # [batch, height, width, channels].

x

<tf.Tensor: shape=(1, 8, 8, 1), dtype=float32, numpy=
array([[[[  3.       ],
         [  3.1666667],
         [  3.5      ],
         [  3.3333333],
         [  3.       ],
         [  2.5      ],
         [  2.       ],
         [  1.75     ]],

        [[  2.1666667],
         [  2.2777777],
         [  2.5      ],
         [  2.3888888],
         [  2.1666667],
         [  1.8333334],
         [  1.5      ],
         [  1.3333334]],

        [[  0.5      ],
         [  1.2777778],
         [  2.8333333],
         [  5.2777777],
         [  7.0555553],
         [  8.166667 ],
         [  7.5      ],
         [  7.1666665]],

        [[  0.5      ],
         [  2.0555556],
         [  5.1666665],
         [ 10.055555 ],
         [ 13.611111 ],
         [ 15.833333 ],
         [ 14.5      ],
         [ 13.833333 ]],

        [[  0.5      ],
         [  2.0555556],
         [  5.1666665],
         [ 10.055555 ],
         [ 13.611111 ],
         [ 15.833333 ],
         [ 14.5      ],
  

In [219]:
import numpy as np
conv_kernel = np.array([[-1, 0, 1],
                        [-1, 0, 1],
                        [-1, 0, 1]])

data_matrix = np.array([
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 2, 2, 1, 1, 1],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9],
    [2, 2, 2, 9, 9, 9, 9, 9]
])

In [218]:

def cov2(data_matrix, conv_kernel, stride, bias, padding, padding_h=1):
    if padding:
        img2d = np.pad(data_matrix,padding_h, mode='constant',
                     constant_values=0)
    else:
        img2d = data_matrix
    inw, inh = img2d.shape
    w, h = conv_kernel.shape
    outwidth = (inw - w) // stride + 1
    outheight = (inh - h) // stride + 1
    arrayy = np.zeros(shape=(outwidth, outheight))
    for i in range(outheight):
        for j in range(outwidth):
            s = 0
            for k in range(w):
                for l in range(h):
                    s += img2d[k + i * stride][l + j * stride] * conv_kernel[k][l]
            arrayy[i][j] = s + bias
    return arrayy


def maxpooling(data_matrix, pool_kernel, stride, padding, padding_h=1):
    if padding:
        img2d = np.pad(data_matrix,padding_h, mode='constant',
                     constant_values=0)
    else:
        img2d = data_matrix
    inw, inh = img2d.shape
    w, h = pool_kernel, pool_kernel
    outwidth = (inw - w) // stride + 1
    outheight = (inh - h) // stride + 1
    arrayy_max = np.zeros(shape=(outwidth, outheight))
    for i in range(outheight):
        for j in range(outwidth):
            s = []
            for k in range(w):
                for l in range(h):
                    small_s = img2d[k + i * stride][l + j * stride]
                    s.append(small_s)
            arrayy_max[i][j] = np.array(s).max()
    return arrayy_max


def avgpooling(data_matrix, pool_kernel, stride, padding, padding_h=1):
    if padding:
        img2d = np.pad(data_matrix,padding_h, mode='constant',
                     constant_values=0)
    else:
        img2d = data_matrix
    inw, inh = img2d.shape
    w, h = pool_kernel, pool_kernel
    outwidth = (inw - w) // stride + 1
    outheight = (inh - h) // stride + 1
    arrayy_avg = np.zeros(shape=(outwidth, outheight))
    for i in range(outheight):
        for j in range(outwidth):
            s = []
            for k in range(w):
                for l in range(h):
                    small_s = img2d[k + i * stride][l + j * stride]
                    s.append(small_s)
            arrayy_avg[i][j] = round(np.array(s).mean(), 4)
    return arrayy_avg


In [210]:
# answer for question 3
conv_value = cov2(data_matrix=data_matrix, conv_kernel=conv_kernel.T, stride=1, bias=0.5,
                    padding='True', padding_h=1)
print(conv_value)  

[[  4.5   6.5   6.5   6.5   5.5   4.5   3.5   2.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   7.5  14.5  22.5  23.5  24.5  16.5]
 [  0.5   0.5   7.5  14.5  22.5  23.5  24.5  16.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5]
 [ -3.5  -5.5 -12.5 -19.5 -26.5 -26.5 -26.5 -17.5]]


In [212]:
# answer for question 4
conv_value_stride2 = cov2(data_matrix=data_matrix, conv_kernel=conv_kernel.T, stride=2, bias=0.5,
                        padding='padding', padding_h=1)
print(conv_value_stride2)  

[[ 4.5  6.5  5.5  3.5]
 [ 0.5  0.5  0.5  0.5]
 [ 0.5  7.5 22.5 24.5]
 [ 0.5  0.5  0.5  0.5]]


In [214]:
# answer for question 5(a)
max_pool_ans = maxpooling(data_matrix=conv_value, pool_kernel=3, stride=1, padding='padding', padding_h=1)
print(max_pool_ans)  

[[ 6.5  6.5  6.5  6.5  6.5  5.5  4.5  3.5]
 [ 6.5  6.5  6.5  6.5  6.5  5.5  4.5  3.5]
 [ 0.5  7.5 14.5 22.5 23.5 24.5 24.5 24.5]
 [ 0.5  7.5 14.5 22.5 23.5 24.5 24.5 24.5]
 [ 0.5  7.5 14.5 22.5 23.5 24.5 24.5 24.5]
 [ 0.5  7.5 14.5 22.5 23.5 24.5 24.5 24.5]
 [ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]
 [ 0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5]]


In [216]:
# answer for question 5(b)
avg_pool_ans = avgpooling(data_matrix=conv_value, pool_kernel=3, stride=1, padding='padding', padding_h=1)
print(avg_pool_ans)  

[[ 1.3333  2.1111  2.3333  2.2222  2.      1.6667  1.3333  0.7778]
 [ 1.4444  2.2778  2.5     2.3889  2.1667  1.8333  1.5     0.8889]
 [ 0.3333  1.2778  2.8333  5.2778  7.0556  8.1667  7.5     4.7778]
 [ 0.3333  2.0556  5.1667 10.0556 13.6111 15.8333 14.5     9.2222]
 [ 0.3333  2.0556  5.1667 10.0556 13.6111 15.8333 14.5     9.2222]
 [ 0.3333  1.2778  2.8333  5.2778  7.0556  8.1667  7.5     4.7778]
 [-0.7778 -2.0556 -3.8333 -6.1667 -7.7222 -8.5    -7.5    -4.6667]
 [-0.8889 -2.2222 -4.     -6.3333 -7.8889 -8.6667 -7.6667 -4.7778]]
